baseURL = "https://arteuro.net"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Atelier Euro - Coming Soon" 
    description = "It's Under Construction..."
    favicon = ""
    message = "COMING SOON !" 
    release = "May 11, 2026"
    background = "" 

socialIcons = [
    {name = "email", url = "support@arteuro.net"},      
    {name = "instagram", url = "https://instagram.com/atelier.euro"}    
] 


